version: "3.5"

services:
  api-web:
    container_name: api-web
    image: node:16-alpine3.11
    build:
      context: .
      target: api-web
    volumes:
      - "./src/:/var/www/src"
    ports:
    - 4445:80

  api-db:
    container_name: api-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
    - mysql-lib:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - 3308:3306

volumes:
  mysql-lib:
