version: "3.5"

services:
  api-web:
    container_name: api-web
    image: node:16-alpine3.11
    build:
      context: .
      target: api-web
    volumes:
      - "./src/:/var/www/src"
    ports:
      - 4445:80
