version: "3.5"

services:
  api:
    container_name: api
    image: node:16-alpine3.11
    build:
      context: .
      target: api
    volumes:
      - "./src/:/var/www/src"
      - "./node_modules/:/var/www/node_modules"
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
    - mysql-lib:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - 3307:3306

volumes:
  mysql-lib:
